port: :8080
proxies:
  - id: self
    name: self
    host: http://localhost:8080/
    
roots:
  - method: GET
    path: /test/:id
    response:
      type: RESPOND
      code: 422
      headers:
        Content-Type: application/json
      body: >-
        {
          "test": "RESPONSE"
        }

  - method: GET
    path: /proxy/path
    response:
      type: PROXY
      proxyId: self
      proxyPath: /test/123
      headers:
        Authorization: BASIC Noop